# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Users/Vivado2023.1/Projects/Memristor_demo/Memristor_demo.srcs/sources_1/ip/floating_point_4/floating_point_4.xci
# IP: The module: 'floating_point_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Users/Vivado2023.1/Projects/Memristor_demo/Memristor_demo.gen/sources_1/ip/floating_point_4/floating_point_4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'floating_point_4'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/Users/Vivado2023.1/Projects/Memristor_demo/Memristor_demo.srcs/sources_1/ip/floating_point_4/floating_point_4.xci
# IP: The module: 'floating_point_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Users/Vivado2023.1/Projects/Memristor_demo/Memristor_demo.gen/sources_1/ip/floating_point_4/floating_point_4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'floating_point_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
