# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/top_xdc.xdc

# IP: ip/floating_point_10/floating_point_10.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==floating_point_10 || ORIG_REF_NAME==floating_point_10} -quiet] -quiet

# IP: ip/floating_point_9/floating_point_9.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==floating_point_9 || ORIG_REF_NAME==floating_point_9} -quiet] -quiet

# IP: ip/floating_point_8/floating_point_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==floating_point_8 || ORIG_REF_NAME==floating_point_8} -quiet] -quiet

# IP: ip/floating_point_7/floating_point_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==floating_point_7 || ORIG_REF_NAME==floating_point_7} -quiet] -quiet

# IP: ip/floating_point_5/floating_point_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==floating_point_5 || ORIG_REF_NAME==floating_point_5} -quiet] -quiet

# IP: ip/floating_point_3/floating_point_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==floating_point_3 || ORIG_REF_NAME==floating_point_3} -quiet] -quiet

# IP: ip/floating_point_2/floating_point_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==floating_point_2 || ORIG_REF_NAME==floating_point_2} -quiet] -quiet

# IP: ip/floating_point_1/floating_point_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==floating_point_1 || ORIG_REF_NAME==floating_point_1} -quiet] -quiet

# IP: ip/clk_wiz_0/clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet
